apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-helm-chart-value-overrides
  namespace: metallb-system
data:
  values.yaml: |-  
    # Default values for metallb.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.2.100-192.168.2.110